
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

#Program Pemesanan Tiket Kereta
#Author : Michael Alfred C. P
#NIM : 215314119


from pathlib import Path
import os
import sys
import gui1

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, ttk, Canvas, Entry, Text, Button, PhotoImage, Toplevel, StringVar, OptionMenu


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


mainWindow = Tk()

mainWindow.geometry("498x206")
mainWindow.title("Pemesanan Tiket Kereta Api")
mainWindow.configure(bg = "#FFFFFF")

def close():
    mainWindow.destroy()

canvas = Canvas(
    mainWindow,
    bg = "#FFFFFF",
    height = 206,
    width = 498,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_bg.png"))
image_1 = canvas.create_image(
    249.0,
    103.0,
    image=image_image_1
)

canvas.create_text(
    21.0,
    23.0,
    anchor="nw",
    text="Stasiun Asal:",
    fill="#000000",
    font=("MontserratRoman Regular", 12 * -1)
)

canvas.create_text(
    243.0,
    98.0,
    anchor="nw",
    text="Dewasa:",
    fill="#000000",
    font=("MontserratRoman Regular", 12 * -1)
)

canvas.create_text(
    372.0,
    98.0,
    anchor="nw",
    text="Bayi:",
    fill="#000000",
    font=("MontserratRoman Regular", 12 * -1)
)

canvas.create_text(
    21.0,
    98.0,
    anchor="nw",
    text="Tanggal Keberangkatan (ddmmyyyy):",
    fill="#000000",
    font=("MontserratRoman Regular", 12 * -1)
)

canvas.create_text(
    280.0,
    26.0,
    anchor="nw",
    text="Stasiun Tujuan:",
    fill="#000000",
    font=("MontserratRoman Regular", 12 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    121.0,
    59.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=23.0,
    y=45.0,
    width=196.0,
    height=26.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_proses.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [print("button_proses clicked"), gui1.func(),].pack(),
    relief="flat"
)
button_1.place(
    x=412.0,
    y=170.0,
    width=68.0,
    height=24.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    374.0,
    59.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=276.0,
    y=45.0,
    width=196.0,
    height=26.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    119.0,
    134.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=21.0,
    y=120.0,
    width=196.0,
    height=26.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    295.0,
    134.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=242.0,
    y=120.0,
    width=106.0,
    height=26.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    423.0,
    134.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=372.0,
    y=120.0,
    width=102.0,
    height=26.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_swap.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [print("button_2 clicked"), swap()],
    relief="flat"
)
button_2.place(
    x=234.0,
    y=44.0,
    width=31.0,
    height=31.0
)

#function swap berfungsi untuk menukar isi dari entry_1 dan entry_2
def swap():
    stasiun1 = entry_1.get()
    stasiun2 = entry_2.get()
    entry_1.delete(0, "end")
    entry_2.delete(0, "end")
    entry_1.insert(0, stasiun2)
    entry_2.insert(0, stasiun1)

mainWindow.resizable(False, False)
mainWindow.mainloop()
