
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, OptionMenu, StringVar, Toplevel
import gui

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame1")
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



def func():

    
    window1 = Toplevel()

    window1.geometry("498x206")
    window1.configure(bg = "#FFFFFF")
    window1.title("Pemesanan Tiket Kereta Api")

    kereta = ["Argo Wilis", "Sawunggalih", "Fajar Utama"]
    kelas = ["Ekonomi", "Bisnis", "Eksekutif"]

    canvas1 = Canvas(
        window1,
        bg = "#FFFFFF",
        height = 206,
        width = 498,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas1.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas1.create_image(
        249.0,
        103.0,
        image=image_image_1
    )

    canvas1.create_text(
        21.0,
        23.0,
        anchor="nw",
        text="Nama Lengkap:",
        fill="#000000",
        font=("MontserratRoman Regular", 12 * -1)
    )

    canvas1.create_text(
        243.0,
        98.0,
        anchor="nw",
        text="Jenis Kereta:",
        fill="#000000",
        font=("MontserratRoman Regular", 12 * -1)
    )

    canvas1.create_text(
        372.0,
        98.0,
        anchor="nw",
        text="Kelas Kereta:",
        fill="#000000",
        font=("MontserratRoman Regular", 12 * -1)
    )

    canvas1.create_text(
        21.0,
        98.0,
        anchor="nw",
        text="Nomor KTP:",
        fill="#000000",
        font=("MontserratRoman Regular", 12 * -1)
    )

    entry_image_6 = PhotoImage(
        file=relative_to_assets("entry_6.png"))
    entry_bg_6 = canvas1.create_image(
        248.5,
        59.0,
        image=entry_image_6
    )
    entry_6 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_6.place(
        x=23.0,
        y=45.0,
        width=451.0,
        height=26.0
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_lanjut.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=412.0,
        y=170.0,
        width=68.0,
        height=24.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_7.png"))
    entry_bg_2 = canvas1.create_image(
        119.0,
        134.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=21.0,
        y=120.0,
        width=196.0,
        height=26.0
    )
    clickedKereta = StringVar()
    drop_3 = OptionMenu(
        canvas1, clickedKereta, *kereta,
    )
    drop_3.place(
        x=242.0,
        y=120.0,
        width=106.0,
        height=26.0
    )

    clickedKelas = StringVar()
    drop_4 = OptionMenu(canvas1, clickedKelas, *kelas)
    drop_4.place(
        x=372.0,
        y=120.0,
        width=102.0,
        height=26.0
    )

    window1.resizable(False, False)
    window1.mainloop()
